apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: cmaxkbqxp-go 
  janus-idp.io/tekton: cmaxkbqxp-go
  backstage.io/kubernetes-id: cmaxkbqxp-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cmaxkbqxp-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  